services:
  - type: web
    name: rcd-bot
    env: python
    region: oregon
    runtime: python:3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8207298018:AAHGHL0LFOc2JBSxyFCKC8hEfd3k3VSMfEs"
      - key: DATABASE_URL
        sync: false
      - key: RENDER
        value: "true"
